config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'journeys/create'
  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard'
  resources :pigeons, only: %i[index new show create destroy] do
    resources :journeys, only: :create
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/journey.rb
# frozen_string_literal: true

class Journey < ApplicationRecord
  belongs_to :user
  belongs_to :pigeon
  validates :arrival_address, presence: true
  validates :message, presence: true
  validates :return_date, presence: true
  geocoded_by :arrival_address
  after_validation :geocode, if: :will_save_change_to_arrival_address?
end

app/models/pigeon.rb
# frozen_string_literal: true

class Pigeon < ApplicationRecord
  include PgSearch::Model
  belongs_to :user
  has_one_attached :photo
  has_many :journeys, dependent: :destroy
  validates :name, presence: true
  validates :breed, presence: true
  validates :km_per_hour, presence: true
  validates :price_per_km, presence: true
  validates :address, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :journeys
  has_many :pigeons, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/journeys_controller.rb
# frozen_string_literal: true

class JourneysController < ApplicationController
  def create
    @pigeon = Pigeon.find(params[:pigeon_id])
    @journey = Journey.new(params_journey)
    @journey.user = current_user
    @journey.pigeon = @pigeon
    @journey.geocode
    @distance = @pigeon.distance_to([@journey.latitude, @journey.longitude])
    @journey.total_price = @distance * @pigeon.price_per_km
    @duration = (@distance / @pigeon.km_per_hour) * 2
    @duration_one_way = @duration / 2
    @journey.return_date = Time.now + @duration.hours
    @journey.arrival_date = Time.now  + @duration_one_way.hours
    @pigeon.available = false
    @pigeon.save
    if @journey.save
      redirect_to dashboard_path(@pigeon)
    else
      render "pigeons/show"
      flash[:alert] = "Your are not connected !"
    end
    authorize @journey
  end

  private

  def params_journey
    params.require(:journey).permit(:arrival_address, :return_date, :message)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home; end

  def dashboard
    @user = current_user
  end
end

app/controllers/pigeons_controller.rb
# frozen_string_literal: true

class PigeonsController < ApplicationController
  def index
    @pigeons = policy_scope(Pigeon).order(created_at: :desc)
    grow = 1
    scope = 10 * grow
    if params[:query].present?
      results = Pigeon.near(params[:query], scope).order(:distance)
      while results.empty?
        grow += 2
        scope += 20 * grow
        results = Pigeon.near(params[:query], scope, units: :km).order(:distance).limit(4)
      end
      @pigeons = results

    else
      @pigeons = Pigeon.all

  end

    @markers = @pigeons.map do |pigeon|
      {
        lat: pigeon.latitude,
        lng: pigeon.longitude,
        infowindow: render_to_string(partial: "info_window", locals: { pigeon: pigeon })
        image_url: helpers.asset_url("piaf.png")
      }
    end
  end

  def new
    @pigeon = policy_scope(Pigeon).order(created_at: :desc)
    @pigeon = Pigeon.new
    authorize @pigeon
  end

  def show
    @pigeon = policy_scope(Pigeon).order(created_at: :desc)

    @pigeon = Pigeon.find(params[:id])
    @journey = Journey.new
    authorize @pigeon
  end

  def create
    @pigeon = policy_scope(Pigeon).order(created_at: :desc)

    @pigeon = Pigeon.new(pigeon_params)
    @pigeon.user_id = current_user.id
    if @pigeon.save
      redirect_to dashboard_path(@pigeon)
    else
      render "new"
    end
    authorize @pigeon
  end

  def destroy
    @pigeon = Pigeon.find(params[:id])
    @pigeon.destroy
        authorize @pigeon

    redirect_to pigeons_path
  end

  private

  def pigeon_params
    params.require(:pigeon).permit(:name, :breed, :km_per_hour, :price_per_km, :user_id, :address, :photo)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/journeys/create.html.erb
<h1>Journeys#create</h1>
<p>Find me in app/views/journeys/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>AIR PIAF</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>
<body>
  <%if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <%= render 'shared/navbar' %>
  <div class="page"><%= yield %></div>


  <%= render 'shared/footer' %>
<% if alert %>
  <p class="alert alert-warning" role="alert"><%= alert %></p>
  <% end %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
  <script src="https://cdn.jsdelivr.net/npm/@mojs/core"></script>
</body>
</html>

app/views/pages/dashboard.html.erb
<h1> PROFIL </h1>
<div class="container">
  <div class="contain">
    <img class="picture" src="https://kitt.lewagon.com/placeholder/users/ssaunier">
  </div>
      <div class="row">
        <div class="col-6">
        <h3>Journey history</h3>
        <% @user.journeys.each do |j| %>
        <div class="card-dashboard" style="background-color: black, linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))">
          <p>------------------------------------------------------------------</p>
          <div class="panneau">
          <h5 style="color: white;">Arrival address !</h5>
            <% j.arrival_address.split("").each do |letter| %>
              <% break if letter == ","  %>
              <div class="letter">
                <p1><%= letter %></p1>
              </div><!--  -->
            <% end  %>
          </div>
          <p>Message: <%=j.message  %></p>
          <p>Price: <%= j.total_price / 100 %> €</p>
          <p>Arrival time: <%= j.arrival_date %></p>

      </div>
      <% end %>
  </div>
    <div class="col-6">
    <h3>Pigeon Army</h3>
    <p>------------------------------------------------------</p>
    <h4>Pigeons in service</h4>
    <% @user.pigeons.each do |pigeon| %>
    <% if pigeon.available == false %>
    <p><%= pigeon.name %></p>
      <p>In service at: <%= pigeon.journeys.last.arrival_address %></p>
      <p>Will be back home: <%= pigeon.journeys.last.return_date %></p>
    <% end %>
    <% end %>
    <p>------------------------------------------------------</p>
    <h4>Pigeons availables</h4>
    <% @user.pigeons.each do |pigeon| %>
    <% if pigeon.available == true %>
    <p><%= pigeon.name %></p>
    <% end %>
    <% end %>
  </div>
</div>
<%= link_to "Create Pigeon ", new_pigeon_path, class: "btn btn-success mt-2" %>
<%= link_to "Back", pigeons_path, class: "btn btn-outline-dark mt-2" %>

app/views/pages/home.html.erb
<div class="background-index">
  <div class="go-to-index">
    <%= link_to "Discover our Pigeon Delivery Army",  pigeons_path, class: "btn btn-outline-dark mt-2"%>
  </div>
</div>

app/views/pigeons/_info_window.html.erb
<p><%=link_to pigeon.name, pigeon_path(pigeon) %></p>
<p><%= pigeon.address %></p>

app/views/pigeons/index.html.erb
  <h1> Index </h1>

<div class="container-fluid" >
  <div class="row">

  <div class="col-12 col-lg-8">
    <div class="search">
    <%= form_tag pigeons_path, method: :get do %>
    <%= text_field_tag :query,
    params[:query],
    class: "form-control", id: "address",
      placeholder: "Where do you want to send your message with a pigeon?"%>
      <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
    </div>
      <div class="cards">
        <% @pigeons.each do |pigeon| %>
        <% if pigeon.journeys.present? %>
        <% if pigeon.journeys.last.return_date < Time.now %>
        <% pigeon.available = true %>
        <% pigeon.save %>
        <% end %>
        <% end %>

        <% if pigeon.available %>

        <div class="card-trip" data-lat="<%= pigeon.latitude %>" data-lng="<%= pigeon.longitude %>">
          <img class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path pigeon.photo.key, crop: :fill %>')"/>

          <h2 class="name-pigeon-index"><%=link_to pigeon.name, pigeon_path(pigeon) %></h2>
          <div class="card-trip-infos">
              <p> Breed : <%= pigeon.breed %></p>
              <p> Speed : <%= pigeon.km_per_hour %></p>
              <p> Address : <%= pigeon.address %></p>
              <% if pigeon.respond_to? :distance? %>
              <p> <%= pigeon.distance.round %> km from your target address</p>
              <% end  %>
          </div>
        </div>
         <% end %>
          <% end %>
      </div>

      </div>
      <div class="col-12 col-lg-4">
        <div
        id="map"
        style="width: 100%;
        height: 600px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pigeons/new.html.erb
<div class="container">
  <div class="row">
      <div class="col-6">
        <div class="background-tyson">
        </div>
      </div>
  <!--   <div class="row justify-content-center"> -->
    <div class="col-md-6">
      <h1>Add a pigeon to your pigeon army</h1>

        <%= simple_form_for @pigeon do |f| %>
        <%= f.input :name %>
        <%= f.input :breed %>
        <%= f.input :km_per_hour %>
        <%= f.input :price_per_km %>
        <%= f.input :address, input_html: {id: "address"} %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
<%= link_to "Back", dashboard_path, class: "btn btn-outline-dark mt-2" %>
</div>

app/views/pigeons/show.html.erb
<div class="container">

  <h1><%= @pigeon.name %></h1>

  <div class="row">
    <div class="col-sm-12 col-md-6">
      <h3>Characteristics</h3>
      <table class="table table-bordered">
        <tbody>
          <thead>
            <th><%= @pigeon.breed %></th>
            <th>In <%= @pigeon.address %> </th>
            <th><%= @pigeon.km_per_hour%> km/h </th>
            <th><%= @pigeon.price_per_km %> ct/km</th>
            <%= cl_image_tag @pigeon.photo.key, height: 300, width: 400, crop: :fill %>
            <%= link_to pigeon_path(@pigeon), method: :delete, data: { confirm: "Are you sure?" } do %>
<i class="fa fa-trash destroy_pigeon"></i>
<% end %>
          </thead>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div class="container">
<%= simple_form_for [@pigeon, @journey] do |j| %>
        <%= j.input  :arrival_address, input_html: {id: "address"} %>
        <%= j.input :message%>
        <%= j.button :submit, class: 'btn btn-primary' %>
        <!-- dois afficher le total_price -->
      <% end %>
</div>

<%= link_to "Back", pigeons_path, class: "btn btn-outline-dark mt-2" %>

app/views/shared/_footer.html.erb
<div class="mt-0 pt-2 pb-1 footer">
<div class="container">

  <div class="row">
    <div class="col-lg-3 col-xs-12 logoap">
      <%= image_tag("logonav.png", width: 100, height: 80, crop: :fill) %>

    </div>
    <div class="col-lg-3 col-xs-12 links">
      <h4 class="mt-lg-0 mt-sm-3">Links</h4>
        <ul class="m-0 p-0">
          <li>- <a href="#">Map</a></li>
          <li>- <a href="#">Our Policy</a></li>

        </ul>
    </div>
    <div class="col-lg-3 col-xs-12 location">
      <h4 class="mt-lg-0 mt-sm-4">Location</h4>
      <p>22, fifth avenue New York</p>
    </div>

    <div class="col-lg-3 col-xs-12">
      <h4 class="mt-lg-0 mt-sm-4">Contact</h4>
      <p class="mb-0"><i class="fa fa-phone mr-3"></i>+336 232 232 12</p>
      <p><i class="fa fa-envelope-o mr-3"></i>airpiafservice@gmail.com</p>

    </div>
  </div>
 </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logonav.png" %>

    <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profil", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>